# Generated by Django 5.2.4 on 2025-07-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sector', models.CharField(choices=[('IT-ITES', 'IT-ITES'), ('Green Jobs', 'Green Jobs')], max_length=50)),
                ('qp_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trainer_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20, unique=True)),
                ('batch_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theory_end_date', models.DateField()),
                ('ojt_start_date', models.DateField()),
                ('ojt_end_date', models.DateField()),
                ('theory_hours', models.IntegerField(default=7)),
                ('ojt_hours', models.IntegerField(default=8)),
                ('no_of_students', models.IntegerField()),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobrole')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='jobrole',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheme'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidate_id', models.CharField(max_length=50, unique=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('marksheet_file', models.FileField(blank=True, null=True, upload_to='marksheets/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
            ],
        ),
    ]
