# Generated by Django 5.2.4 on 2025-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='assessment_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='assessment_document',
            field=models.FileField(blank=True, null=True, upload_to='assessment_docs/'),
        ),
        migrations.AddField(
            model_name='batch',
            name='assessor_aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='assessor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='attendance_sheet',
            field=models.FileField(blank=True, null=True, upload_to='attendance/'),
        ),
        migrations.AddField(
            model_name='batch',
            name='candidates_assessed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='candidates_passed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_assessment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='ojt_file',
            field=models.FileField(blank=True, null=True, upload_to='ojt_files/'),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessment_agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessment_document',
            field=models.FileField(blank=True, null=True, upload_to='reassessment_docs/'),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessment_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Re-assessment', 'Re-assessment')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessor_aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassessor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='reassigned_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
